{{- $root := . }}
{{- $ns := splitList .Values.separator .Values.namespaces }}
{{- range compact $ns }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ trim . }}
  labels: {{- include "labels" $root | nindent 4 }}
  annotations:
    # do not delete  namespace when  deleting argocd application
    argocd.argoproj.io/sync-options: Delete=false
{{- end }}
