{{- $root := . }}
{{- $ns := splitList "|" .Values.namespaces }}
{{- range compact $ns }}
---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ . }}
  labels: {{- include "labels" $root | nindent 4 }}
{{- end }}
